# ==============================================================================
# ==============================================================================

library(readr)
library(dplyr)
library(ggplot2)
library(car)
library(ARTool)

# Load the dataset generated by the LLM
df <- read_csv("Simulated_Digital_Twins_Dataset_Optimized.csv")
df <- na.omit(df)

# ---------------------------------------------------------

df$Market_Context <- as.factor(df$Market_Context)
df$Transparency <- as.factor(df$Transparency)
df$Willingness_to_Invest <- as.numeric(df$Willingness_to_Invest)
df$Tech_Savviness <- as.numeric(df$Tech_Savviness) # Remains continuous for the ANCOVA

median_lit <- median(df$Financial_Literacy, na.rm = TRUE)
df <- df %>%
  mutate(Fin_Lit_Cat = ifelse(Financial_Literacy > median_lit, "High", "Low"))
df$Fin_Lit_Cat <- as.factor(df$Fin_Lit_Cat)

# ---------------------------------------------------------

cat("\n--- CHECKS ---\n")

ks_result <- ks.test(df$Willingness_to_Invest, "pnorm", 
                     mean = mean(df$Willingness_to_Invest), 
                     sd = sd(df$Willingness_to_Invest))
print(ks_result)

cat("\nCorrelation between Literacy and Tech: ", cor(df$Financial_Literacy, df$Tech_Savviness, use="complete.obs"), "\n")

cat("\nProfile count per experimental cell:\n")
table(df$Market_Context, df$Transparency, df$Fin_Lit_Cat)

# ---------------------------------------------------------

cat("\n--- STATISTICS ---\n")
mean_table <- df %>%
  group_by(Market_Context, Transparency, Fin_Lit_Cat) %>%
  summarise(
    N = n(),
    Mean = round(mean(Willingness_to_Invest, na.rm = TRUE), 2),
    SD = round(sd(Willingness_to_Invest, na.rm = TRUE), 2),
    .groups = 'drop'
  ) %>%
  arrange(Market_Context, Transparency, Fin_Lit_Cat)

print(as.data.frame(mean_table))

# ---------------------------------------------------------

cat("\n--- 1. PARAMETRIC ANCOVA (Type III Sum of Squares) ---\n")
normal_model <- lm(Willingness_to_Invest ~ Market_Context * Transparency * Fin_Lit_Cat + Tech_Savviness, data = df)
normal_results <- Anova(normal_model, type = "III")
print(normal_results)

# ---------------------------------------------------------

cat("\n--- 2. 3-WAY ART ANOVA (Robust Non-Parametric) ---\n")
art_model <- art(Willingness_to_Invest ~ Market_Context * Transparency * Fin_Lit_Cat, data = df)
art_results <- anova(art_model)
print(art_results)

# ---------------------------------------------------------

cat("\n--- 3. POST-HOC TEST (Bonferroni) ---\n")
post_hoc_art <- art.con(art_model, "Market_Context:Transparency:Fin_Lit_Cat", adjust = "bonferroni")
print(post_hoc_art)

# ---------------------------------------------------------

plot_3way <- ggplot(mean_table, aes(x = Market_Context, y = Mean, color = Transparency, group = Transparency)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 4) +
  facet_wrap(~ Fin_Lit_Cat, labeller = label_both) + 
  theme_minimal() +
  labs(title = "Willingness to Invest by Financial Literacy Level",
       subtitle = "(Mean Willingness to Invest across scenarios)",
       x = "Market Context",
       y = "Willingness to Invest (1-7)",
       color = "Algorithm Type") +
  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +
  theme(text = element_text(size = 12),
        legend.position = "bottom",
        strip.background = element_rect(fill = "lightgray"),
        strip.text = element_text(face = "bold"))

print(plot_3way)
